app = "langler"
primary_region = "ewr"

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "/app/bin/migrate"

[env]
  MIX_ENV = "prod"
  PHX_SERVER = "true"
  PORT = "4000"
  LANG = "en_US.UTF-8"
  POOL_SIZE = "10"
  ECTO_IPV6 = "true"

[[services]]
  internal_port = 4000
  protocol = "tcp"
  force_https = true

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.http_checks]]
    path = "/"
    method = "get"
    interval = 10000
    timeout = 2000
